---
abstract: unknown
author:
  - 'Fergal Daly <fergal@esatclear.ie>'
build_requires:
  ExtUtils::MakeMaker: '0'
  Test::More: '0'
  Test::NoWarnings: '0.02'
  Test::Tester: '0.04'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.04, CPAN::Meta::Converter version 2.143240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Test-Deep
no_index:
  directory:
    - t
    - inc
requires:
  List::Util: '1.09'
  Scalar::Util: '1.09'
  Test::Builder: '0'
resources:
  MailingList: http://lists.perl.org/list/perl-qa.html
  homepage: http://github.com/rjbs/Test-Deep/
  license: http://dev.perl.org/licenses/
version: '0.114'
